linters:
  enable:
    - dupl
    - funlen
    - goconst
    - gocyclo
    - gosec
    - unconvert
  disable:
    - gochecknoglobals
    - gochecknoinits
    - lll
    - cyclop

linters-settings:
  cyclop:
    max-complexity: 15
  errcheck:
    check-type-assertions: true
    check-blank: false
  funlen:
    lines: 200
    statements: 100
  gocyclo:
    min-complexity: 40
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    excludes:
      - G103
  govet:
    enable:
      - printf
      - shift
      - structtag
    disable:
      - composites
      - unsafeptr

issues:
  exclude-rules:
    - linters:
        - gosec
      path: .*\.go
      text: Use of unsafe calls should be audited
    - linters:
        - govet
      path: _test\.go
      text: possible misuse of unsafe.Pointer
    - linters:
        - cyclop
      path: _test\.go
  exclude-dirs:
    - vendor
    - examples
  max-issues-per-linter: 0
  max-same-issues: 0
