version: "2"

run:
  skip-dirs:
    - examples

linters:
  enable:
    - cyclop
    - dupl
    - funlen
    - goconst
    - gocyclo
    - gosec
    - unconvert
  disable:
    - gochecknoglobals
    - gochecknoinits
    - lll
  settings:
    cyclop:
      max-complexity: 15
    errcheck:
      check-type-assertions: true
      check-blank: false
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 3
      min-occurrences: 3
    gosec:
      excludes:
        - G103
    govet:
      enable:
        - printf
        - shift
        - structtag
      disable:
        - composites
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        path: .*\.go
        text: Use of unsafe calls should be audited
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/darkace1998/Golang-Vulkan-api
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
