linters:
  enable:
    - dupl
    - funlen
    - goconst
    - gocyclo
    - gosec
    - unconvert
  disable:
    - gochecknoglobals
    - gochecknoinits
    - lll
    - cyclop
linters-settings:
  cyclop:
    max-complexity: 15
  errcheck:
    check-type-assertions: true
    check-blank: false
  funlen:
    lines: 200
    statements: 100
  gocyclo:
    min-complexity: 40
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    excludes:
      - G103
  govet:
    enable:
      - printf
      - shift
      - structtag
    disable:
      - composites
      - unsafeptr
